name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: self-hosted

    strategy:
      matrix:
        python-version: [3.9, 3.8]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: python -m pytest addition.py
      
    - name: Create Artifact
      run: |
        mkdir -p artifact
        # Copy the 'addition.py' file and other necessary files into the artifact directory
        #cp code/addition.py artifact/  # Copy 'addition.py' file
        cp -r addition.py artifact/
        
        echo "Packaged Python code for artifact publishing."
        ls -al artifact  # List the contents of the artifact directory to verify
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: python-code-artifact
        path: artifact/

